import pandas as pd
from typing import List
from .schema import ProductInput, SupplierInput, InventoryConfig, InventoryInput, ForecastInput
from .engine import InventoryDecisionEngine

class InventorySimulator:
    def __init__(self, config: InventoryConfig = None):
        self.engine = InventoryDecisionEngine(config)
        self.kpis = {}

    def simulate(self, df_history: pd.DataFrame, product: ProductInput, supplier: SupplierInput, initial_stock: int = 100):
        """
        Runs a chronological backtest simulation.
        df_history must contain chronologically sorted 'date' and 'sales' columns.
        """
        current_stock = initial_stock
        incoming_orders = [] # list of dicts: {'arrive_day': int, 'quantity': int}
        
        stockouts = 0
        total_demand = 0
        fulfilled_demand = 0
        total_inventory_carried = 0
        overstock_days = 0
        
        sim_log = []
        
        # In a real rigorous simulation, we'd predict forecasts step-by-step. 
        # Here we use perfect foresight or naive averages for simplicity just to demonstrate backtesting policy.
        
        for day, row in enumerate(df_history.to_dict('records')):
            actual_demand = row['sales']
            
            # Process received orders
            received_today = sum(o['quantity'] for o in incoming_orders if o['arrive_day'] == day)
            current_stock += received_today
            
            incoming_orders = [o for o in incoming_orders if o['arrive_day'] > day]
            incoming_quantity = sum(o['quantity'] for o in incoming_orders)
            
            # Fulfill demand
            total_demand += actual_demand
            if current_stock >= actual_demand:
                fulfilled_demand += actual_demand
                current_stock -= actual_demand
            else:
                fulfilled_demand += current_stock
                stockouts += 1
                current_stock = 0
                
            total_inventory_carried += current_stock
            if current_stock > 3 * max(1, actual_demand):
                overstock_days += 1
                
            # Engine Decision (use rolling average for naive forecast if no forecast provided)
            # In real system you pass the actual predicted forecast generated by ML
            naive_forecast = max(1, df_history.iloc[max(0, day-7):day]['sales'].mean() if day > 0 else actual_demand)
            naive_forecast = int(naive_forecast)
            
            inv_input = InventoryInput(current_stock=current_stock, incoming_stock=incoming_quantity, reserved_stock=0)
            fcst_input = ForecastInput(predicted_demand=naive_forecast * 7, forecast_horizon=7)
            
            decision = self.engine.process_single(product, inv_input, fcst_input, supplier)
            
            if decision.stock_status in ['REORDER', 'CRITICAL'] and decision.recommended_order > 0:
                incoming_orders.append({
                    'arrive_day': day + supplier.lead_time_days,
                    'quantity': decision.recommended_order
                })
                
            sim_log.append({
                'day': day,
                'demand': actual_demand,
                'received': received_today,
                'end_stock': current_stock,
                'decision': decision.stock_status,
                'order_placed': decision.recommended_order
            })
            
        service_level = (fulfilled_demand / total_demand) if total_demand > 0 else 1.0
        
        self.kpis = {
            'Stockout Rate': f"{(stockouts / len(df_history))*100:.1f}%",
            'Service Level (Fill Rate)': f"{service_level*100:.1f}%",
            'Average Inventory': total_inventory_carried / len(df_history),
            'Overstock Rate': f"{(overstock_days / len(df_history))*100:.1f}%"
        }
        
        return pd.DataFrame(sim_log), self.kpis
